module.exports = {
  appId: 'com.orqium.comandaflow.manager',
  productName: 'ComandaFlow Gestor',
  copyright: 'Copyright 2024-2026 Orqium. Todos os direitos reservados.',
  asar: true,
  compression: 'normal',
  icon: 'build/icon',
  directories: {
    buildResources: 'build',
    output: 'dist/manager',
  },
  extraMetadata: {
    main: 'electron-manager-main.js',
  },
  files: [
    'electron-main.js',
    'electron-manager-main.js',
    'package.json',
    'backend/**/*',
    'frontend/dist/**/*',
    'build/**/*',
    '!backend/.env',
    '!backend/.env.*',
    '!backend/node_modules/**/*',
    '!backend/dev.db',
    '!backend/test/**/*',
    '!backend/frontend/**/*',
    '!backend/backend/**/*',
  ],
  extraResources: [
    { from: '.desktop-runtime/backend/node_modules', to: 'app/backend/node_modules' },
    { from: '.secrets/license-private.pem', to: 'license-private.pem' },
  ],
  win: {
    target: [{ target: 'nsis', arch: ['x64'] }],
    icon: 'build/icon.ico',
    requestedExecutionLevel: 'asInvoker',
    artifactName: 'ComandaFlow-Gestor-Setup-${version}.${ext}',
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true,
    allowElevation: true,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'ComandaFlow Gestor',
    installerIcon: 'build/icon.ico',
    uninstallerIcon: 'build/icon.ico',
    installerHeaderIcon: 'build/icon.ico',
    language: '1046',
    runAfterFinish: true,
    menuCategory: 'Orqium',
  },
};
