import { useCallback, useEffect, useState } from 'react';
import { Activity, Check, Circle, Clock3, CreditCard, Headphones, History, ListChecks, RefreshCw, Server, X } from 'lucide-react';
import api from '../../../shared/services/api';

const dateTime = (value) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0));

export default function SubscriberProfileModal({ subscriberId, canWrite, onClose, onChanged }) {
  const [profile, setProfile] = useState(null);
  const [tab, setTab] = useState('overview');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [savingStep, setSavingStep] = useState('');
  const load = useCallback(async () => {
    setLoading(true);
    try { const response = await api.get(`/manager/subscribers/${subscriberId}/profile`); setProfile(response.data); setError(''); }
    catch (requestError) { setError(requestError.response?.data?.message || 'Não foi possível abrir a ficha do assinante.'); }
    finally { setLoading(false); }
  }, [subscriberId]);
  useEffect(() => { load(); }, [load]);
  const toggleStep = async (step) => {
    if (!canWrite || step.automatic) return;
    setSavingStep(step.key);
    try {
      const response = await api.patch(`/manager/subscribers/${subscriberId}/onboarding/${step.key}`, { completed: !step.completed });
      setProfile((value) => ({ ...value, onboarding: response.data.onboarding, health: { ...value.health, onboarding: response.data.onboarding } }));
      onChanged?.();
    } catch (requestError) { setError(requestError.response?.data?.message || 'Não foi possível atualizar a etapa.'); }
    finally { setSavingStep(''); }
  };
  const tabs = [['overview', 'Resumo', Activity], ['onboarding', 'Onboarding', ListChecks], ['timeline', 'Linha do tempo', History]];

  return <div className="manager-modal-overlay fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="manager-modal-card flex w-full max-w-5xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl" role="dialog" aria-modal="true" aria-label="Ficha do assinante"><header className="flex shrink-0 items-start justify-between gap-3 border-b border-slate-100 p-5"><div className="min-w-0"><h2 className="text-lg font-extrabold text-slate-900">{profile?.subscriber?.businessName || 'Ficha do assinante'}</h2><p className="mt-1 text-sm text-slate-500">Visão completa de saúde, implantação e histórico.</p></div><div className="flex gap-2"><button className="btn-icon" onClick={load} title="Atualizar"><RefreshCw size={18} /></button><button className="btn-icon" onClick={onClose} aria-label="Fechar"><X size={19} /></button></div></header>
    <div className="flex shrink-0 gap-1 overflow-x-auto border-b border-slate-100 px-5 py-2">{tabs.map(([key, label, Icon]) => <button key={key} className={`inline-flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${tab === key ? 'bg-slate-900 text-white' : 'text-slate-500 hover:bg-slate-100'}`} onClick={() => setTab(key)}><Icon size={15} />{label}</button>)}</div>
    <div className="manager-modal-body overflow-y-auto p-5">
      {error && <div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
      {loading && <div className="p-12 text-center text-sm text-slate-500">Carregando ficha...</div>}
      {!loading && profile && tab === 'overview' && <div className="space-y-5">
        <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase text-slate-500">Pulse</p><p className="mt-2 text-3xl font-extrabold text-slate-900">{profile.health.score}<small className="text-xs text-slate-400">/100</small></p></article><article className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase text-slate-500">Conexão</p><p className={`mt-2 font-extrabold ${profile.health.online ? 'text-emerald-700' : 'text-amber-700'}`}>{profile.health.online ? 'Online' : 'Offline'}</p><p className="mt-1 text-xs text-slate-500">{dateTime(profile.health.lastSyncAt)}</p></article><article className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase text-slate-500">Onboarding</p><p className="mt-2 text-2xl font-extrabold text-slate-900">{profile.onboarding.percentage}%</p><p className="mt-1 text-xs text-slate-500">{profile.onboarding.completed} de {profile.onboarding.total} etapas</p></article><article className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase text-slate-500">Contato</p><p className="mt-2 truncate font-bold text-slate-800">{profile.subscriber.contactName || 'Sem responsável'}</p><p className="mt-1 truncate text-xs text-slate-500">{profile.subscriber.email}</p></article></section>
        <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2 font-extrabold text-slate-900"><Server size={18} className="text-blue-600" />Assinaturas e dispositivos</div><div className="mt-3 space-y-2">{profile.subscriptions.slice(0, 4).map((item) => <div key={item.id} className="rounded-lg bg-slate-50 p-3 text-sm"><div className="flex justify-between gap-3"><strong>{item.plan}</strong><span className="status-chip bg-slate-200 text-slate-700">{item.status}</span></div><p className="mt-1 text-xs text-slate-500">Validade: {dateTime(item.expiresAt)} · {item.installations?.length || 0} dispositivo(s)</p></div>)}{!profile.subscriptions.length && <p className="text-sm text-slate-500">Nenhuma assinatura emitida.</p>}</div></div><div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2 font-extrabold text-slate-900"><CreditCard size={18} className="text-amber-600" />Últimas cobranças</div><div className="mt-3 space-y-2">{profile.charges.slice(0, 4).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 p-3 text-sm"><div><strong>{item.description || 'Mensalidade'}</strong><p className="text-xs text-slate-500">Vence em {dateTime(item.dueDate)}</p></div><div className="text-right"><strong>{money(item.amount)}</strong><p className="text-xs text-slate-500">{item.status}</p></div></div>)}{!profile.charges.length && <p className="text-sm text-slate-500">Nenhuma cobrança registrada.</p>}</div></div></section>
        <section className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2 font-extrabold text-slate-900"><Headphones size={18} className="text-orange-600" />Chamados recentes</div><div className="mt-3 grid gap-2 md:grid-cols-2">{profile.tickets.slice(0, 4).map((ticket) => <div key={ticket.id} className="rounded-lg bg-slate-50 p-3"><div className="flex justify-between gap-2"><strong className="text-sm text-slate-800">{ticket.subject}</strong><span className="text-xs font-bold text-slate-500">{ticket.status}</span></div><p className="mt-1 text-xs text-slate-500">{ticket.priority} · {dateTime(ticket.updatedAt)}</p></div>)}{!profile.tickets.length && <p className="text-sm text-slate-500">Nenhum chamado registrado.</p>}</div></section>
      </div>}
      {!loading && profile && tab === 'onboarding' && <div className="space-y-4"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex justify-between text-sm font-extrabold text-emerald-900"><span>Progresso da implantação</span><span>{profile.onboarding.percentage}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-emerald-100"><div className="h-full rounded-full bg-emerald-600 transition-all" style={{ width: `${profile.onboarding.percentage}%` }} /></div></div><div className="grid gap-2">{profile.onboarding.steps.map((step) => <button key={step.key} type="button" disabled={!canWrite || step.automatic || savingStep === step.key} onClick={() => toggleStep(step)} className={`flex items-start gap-3 rounded-xl border p-4 text-left ${step.completed ? 'border-emerald-200 bg-emerald-50/50' : 'border-slate-200 bg-white'} ${!step.automatic && canWrite ? 'hover:border-emerald-300' : 'cursor-default'}`}><span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${step.completed ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-400'}`}>{step.completed ? <Check size={15} /> : <Circle size={14} />}</span><span className="min-w-0 flex-1"><strong className="block text-sm text-slate-900">{step.label}</strong><small className="mt-1 block text-xs leading-5 text-slate-500">{step.description}</small>{step.completedAt && <small className="mt-1 block text-[11px] font-semibold text-emerald-700">Concluído em {dateTime(step.completedAt)} · {step.source === 'automatico' ? 'detectado automaticamente' : step.completedBy || 'Gestor'}</small>}</span>{step.automatic && <span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold uppercase text-blue-700">Automática</span>}</button>)}</div></div>}
      {!loading && profile && tab === 'timeline' && <div className="space-y-2">{profile.timeline.map((event) => <article key={event.id} className="flex gap-3 rounded-xl border border-slate-200 p-4"><div className="mt-0.5 rounded-lg bg-slate-100 p-2 text-slate-600"><Clock3 size={16} /></div><div><p className="font-bold text-slate-900">{event.title}</p><p className="mt-1 text-sm text-slate-600">{event.detail}</p><p className="mt-1 text-xs text-slate-400">{dateTime(event.at)}</p></div></article>)}{!profile.timeline.length && <p className="p-10 text-center text-slate-500">Nenhum evento registrado.</p>}</div>}
    </div>
  </section></div>;
}
